# Spring properties
spring:
  application:
     name: customer-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8999/eureka/

# HTTP Server
server:
  port: 8083   # HTTP (Tomcat) port
  